title: Bodega Giacometti
email: contacto@bodegagiacometti.com
description: >-
  Bodega Giacometti (República del Paraguay)
baseurl: ""
url: "https://www.bodegagiacometti.com"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
